name: Tests and formatter

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install pipenv
    - name: Create virtual environment with dependencies
      run: |
        python -m pipenv install
    - name: Use Black
      run: |
        pipenv run black -l 119 .
    - name: Flake
      run: |
        pipenv run flake8
    - name: Test
      run: |
        pipenv run pytest
